# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.0.4'

gem 'rails', '~> 7.1.3'

gem 'lograge'
gem 'prometheus_exporter'
gem 'puma', '>= 5.0'
gem 'sqlite3', '~> 1.4'

group :development, :test do
  gem 'debug', platforms: %i[mri mswin mswin64 mingw x64_mingw]
end

group :development do
end
